image: dsferruzza/php-node-build

before_script:
  - apt-get update -yqq
  - apt-get install -yqq libfontconfig apt-utils php5-mysql php5-curl
  - cp gitlab.env .env
  - php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - php -r "unlink('composer-setup.php');"
  - php -v
  - git --version
  - composer --version
  - composer self-update
  - composer install --no-interaction --optimize-autoloader
  - ping -c 3 mysql

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: lumen-vue
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: lumen-vue
  MYSQL_PASSWORD: secret
  COMPOSER_HOME: /cache/composer

cache:
  paths:
    - node_modules/

#connect:
#  image: mysql
#  script:
#  - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

test_acync:
  script:
    - npm install
    - npm test

test_php:
  script:
    - php artisan migrate
    - ./vendor/bin/phpcs
    - ./vendor/bin/phpunit
