# image: node:latest
image: dsferruzza/php-node-build

# services:
#   - mysql:latest

cache:
  paths:
    - node_modules/

test_acync:
  script:
    - npm install
    - npm test

test_php:
  script:
    - composer update
    - ./vendor/bin/phpunit
