image: dsferruzza/php-node-build

before_script:
  - apt-get update
  - apt-get install -y libfontconfig apt-utils php5-mysql php5-curl
  - cp gitlab.env .env
  - which php
  - php artisan key:generate
  - php artisan config:cache
  - php artisan migrate

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: lumen-vue
  MYSQL_ROOT_PASSWORD: secret

cache:
  paths:
    - node_modules/

#connect:
#  image: mysql
#  script:
#  - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

test_acync:
  script:
    - npm install
    - npm test

test_php:
  script:
    - composer update
    - ./vendor/bin/phpcs
    - ./vendor/bin/phpunit
